language: python

matrix:
  include:
  - os: linux
    python: 3.6
    dist: xenial
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='tests/travis/testing.sh'
  - os: linux
    python: 3.6
    dist: bionic
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='tests/travis/testing.sh'
  - os: linux
    python: 3.7
    dist: bionic
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='tests/travis/testing.sh'

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a

install:
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - $PIP_CMD
  - conda info -a

after_success:
  - coveralls

script:
  - travis_wait 40 bash $TEST_CMD

notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always